export const exercises = [
    {
        id:2,
        name: 'incline bench press . barbell',
        focusArea: 'chest',
        img: './images/chest/inclineBenchPressBarbellIcon.png',
        detailedImage: './images/chest/inclineBenchPressBarbell.png',
        equipment: [{name: 'Barbel'}, {name: 'incline Bench'}],
        preperation:'Lie on a bench with feet on the floor. Hold the barbell above your chest with elbows bent at 90 degrees and palms facing forward.',
        keyTips: [ {details: 'Do not lock your elbows at the top.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:3,
        name: 'Bench Press . Barbell',
        focusArea: 'chest',
        img: './images/chest/benchPressBarbellIcon.jpg',
        detailedImage: './images/chest/benchPressBarbell.jpg',
        equipment: [{name: 'Barbell'}, {name: 'Flat Bench'}],
        preperation:'Lie on a bench with feet on the floor. Hold the bar at the height of the chest with hands wider than shoulder width apart, arms bent and palms facing forward',
        keyTips: [ {details: 'Do not lock your elbows at the top.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:5,
        name: 'bench fly . cable',
        focusArea: 'chest',
        img: './images/chest/benchFlyCableIcon.jpg',
        detailedImage: './images/chest/benchFlyCable.jpg',
        equipment: [{name: 'flat bench'}, {name: 'cable machine'}],
        preperation:'Lie on a bench with your chest lined up with the machine pulleys. Hold a handle in each hand with palms up and extend your arms to the sides.',
        keyTips: [ {details: 'Don not use your biceps at the top position.'}, { details: 'Keep your elbows slightly bent throughout the movement.'}, { details: 'Keep a straight back during the exercise.'}],
    },
    {
        id:6,
        name: 'bench fly . dumbbell',
        focusArea: 'chest',
        img: './images/chest/benchFlyDumbbellIcon.png',
        detailedImage: './images/chest/benchFlyDumbbell.png',
        equipment: [{name: 'flat bench'}, {name: 'dumbbell'}],
        preperation:'Lie on a bench with feet on the floor. Hold a dumbbell in each hand in a neutral grip and extend your arms to the sides.',
        keyTips: [ {details: 'Do not use your biceps at the top position.'}, { details: 'Keep your elbows slightly bent throughout the movement.'}, { details: 'Keep a straight back during the exercise.'}],
    },
    // {
    //     id:7,
    //     name: 'bench press(close grip) . babell',
    //     focusArea: 'chest',
    //     img: './images/shoulder/lateralRaiseIcon.jpg',
    //     detailedImage: './images/shoulder/lateralRaise.jpg',
    //     equipment: [{name: 'flat bench'}, {name: 'barbell'}],
    //     preperation:'Lie on a bench with feet on the floor. Hold the barbell at the height of the chest in a close overhand grip with arms bent.',
    //     keyTips: [ {details: 'Do not lock your elbows at the top.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    // },
    // {
    //     id:8,
    //     name: 'bench press(close grip) . dumbbell',
    //     focusArea: 'chest',
    //     img: './images/shoulder/lateralRaiseIcon.jpg',
    //     detailedImage: './images/shoulder/lateralRaise.jpg',
    //     equipment: [{name: 'flat bench'}, {name: 'dumbbell'}],
    //     preperation:'Lie on a bench with feet on the floor. Hold a dumbbell in each hand in a shoulder width neutral grip at the height of the chest with arms bent.',
    //     keyTips: [ {details: 'Do not lock your elbows at the top.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    // },
    {
        id:9,
        name: 'bench press . cable',
        focusArea: 'chest',
        img: './images/chest/benchPressCableIcon.jpg',
        detailedImage: './images/chest/benchPressCable.jpg',
        equipment: [{name: 'flat bench'}, {name: 'cable machine'}],
        preperation:'Lie on a bench with feet on the floor. Hold one handle in each hand in a shoulder width neutral grip with your elbows bent on each side of your chest.',
        keyTips: [ {details: 'Do not lock your elbows at the top.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:10,
        name: 'bench press . dumbbell',
        focusArea: 'chest',
        img: './images/chest/benchPressDumbbellIcon.jpg',
        detailedImage: './images/chest/benchPressDumbbell.jpg',
        equipment: [{name: 'flat bench'}, {name: 'dumbbell'}],
        preperation:'Lie on a bench with feet on the floor. Hold one dumbbell in each hand with elbows bent and palms facing forward on each side of your chest.',
        keyTips: [ {details: 'Do not lock your elbows at the top.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:11,
        name: 'bench press . smith machine',
        focusArea: 'chest',
        img: './images/chest/BenchPressSmithMachineIcon.jpg',
        detailedImage: './images/chest/BenchPressSmithMachine.jpg',
        equipment: [{name: 'flat bench'}, {name: 'smith machine'}],
        preperation:'Lie on a bench with feet on the floor. Hold the bar over your chest in a shoulder width grip with arms bent and palms facing forward.',
        keyTips: [ {details: 'Do not lock your elbows at the top.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:12,
        name: 'chest dip',
        focusArea: 'chest',
        img: './images/chest/chestDipIcon.jpg',
        detailedImage: './images/chest/chestDip.jpg',
        equipment: [{name: 'bodyweight'}],
        preperation:'Stand in front of the machine with feet shoulder width apart. Hold the handle with two hands and arms stretched.',
        keyTips: [ {details: 'Pull the handle horizontally.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:13,
        name: 'close-Grip push-up',
        focusArea: 'triceps',
        img: './images/triceps/closeGripPushUpsIcon.png',
        detailedImage: './images/triceps/closeGripPushUps.png',
        equipment: [{name: 'bodyweight'}],
        preperation:'Lie prone on the floor with feet together. Put your hands directly under shoulders and extend your arms. Form a straight line from head to toe.',
        keyTips: [ {details: 'Avoid your elbows pointing outward to keep shoulders, elbows and hands aligned.'}, { details: 'Do not fully extend your arms.'}, { details: 'Do no let your chest touch the floor.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:14,
        name: 'around the world . dumbbell',
        focusArea: 'chest',
        img: './images/chest/aroundTheWorld.jpg',
        detailedImage: './images/chest/aroundTheWorld.jpg',
        equipment: [{name: 'dumbbell'}, {name: 'incline bench'}],
        preperation:'Lie on a bench with feet on the floor. Hold a dumbbell above your thighs in each hand with palms facing up.',
        keyTips: [ { details: 'Keep your elbows slightly bent throughout the movement.'}, { details: 'Do not shrug your shoulders when raising arms up.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:15,
        name: 'incline bench fly . cable',
        focusArea: 'chest',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'cable machine'}, {name: 'incline bench'}],
        preperation:'Lie on a bench with feet on the floor. Hold the handles with palms up and extend your arms to the sides.',
        keyTips: [ { details: 'Keep your elbows slightly bent throughout the movement.'}, { details: 'Do not use your biceps at the top position.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:16,
        name: 'incline bench fly . dumbbell',
        focusArea: 'chest',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'dumbbell'}, {name: 'incline bench'}],
        preperation:'Lie on a bench with feet on the floor. Hold a dumbbell with palms up and extend your arms to the sides.',
        keyTips: [ { details: 'Keep your elbows slightly bent throughout the movement.'}, { details: 'Do not use your biceps at the top position.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:17,
        name: 'incline bench press . cable',
        focusArea: 'chest',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'cable machine'}, {name: 'incline bench'}],
        preperation:'Lie on a bench with feet on the floor. Hold a handle in each hand at the height of the chest with elbows bent 90 degrees and palms facing forward.',
        keyTips: [ { details: 'Do not lock out your elbows at the top.'}, { details: 'Do not open your arms too far when lowering.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:18,
        name: 'incline bench press . dumbbell',
        focusArea: 'chest',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'dumbbell'}, {name: 'incline bench'}],
        preperation:'Lie on a bench with feet on the floor. Hold a dumbbell in each hand at the height of the chest with elbows bent 90 degrees and palms facing forward.',
        keyTips: [ { details: 'Do not lock out your elbows at the top.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:19,
        name: 'pec deck fly . machine',
        focusArea: 'chest',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'pec deck machine'}],
        preperation:'Sit on the machine with back supported and feet on the floor. Hold the hnadles with palms facing forward. Bend your elbows at 90 degrees with forearms against the pads.',
        keyTips: [ { details: 'Do not let your hands touch each otheer during the exercise.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:20,
        name: 'pullover . dumbbell',
        focusArea: 'chest',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'dumbbell'}, {name: 'flat bench'}],
        preperation:'Lie your upper back on a bench with your legs and feet planted on the floor. Hold the dumbbell using both hands and press it over your chest with arms stretched.',
        keyTips: [ { details: 'Do not let your hands touch each otheer during the exercise.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:21,
        name: 'standing chest fly . cable',
        focusArea: 'chest',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'cable machine'}],
        preperation:'stand with your back to the machine with one foot in front of the other. Hold the handles with palms facing forward and extend your arms to the sides.',
        keyTips: [ { details: 'Keep your elbows slightly bent throughout the movement.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:22,
        name: 'standing decline fly . cable',
        focusArea: 'chest',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'cable machine'}],
        preperation:'stand with your back to the machine with one foot in front of the other. Hold the handles with palms facing forward and extend your arms to the sides.',
        keyTips: [ { details: 'Keep your elbows slightly bent throughout the movement.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:23,
        name: 'standing incline fly . cable',
        focusArea: 'chest',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'cable machine'}],
        preperation:'stand with your back to the machine with one foot in front of the other. Hold the handles with palms facing forward and extend your arms to the sides.',
        keyTips: [ { details: 'Keep your elbows slightly bent throughout the movement.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:24,
        name: 'standing chest press . cable',
        focusArea: 'chest',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'cable machine'}],
        preperation:'stand with your back to the machine with one leg in front and knes=es bent. Bring the handles to your chest with arms bent and palms down.',
        keyTips: [ { details: 'Do not lock your elbows during the exercise.'},{ details: 'Keep your elbows, wrists and shoulders at the same height.'}, { details: 'Keep a braced core during the exercise.'}],
    },
    {
        id:25,
        name: 'bench press (Close Grip) . Barbell',
        focusArea: 'triceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'flat bench'}, {name: 'barbell'}],
        preperation:'Lie on a bench with feet on the floor. Hold the barbell at the height of the chest in a close overhand grip with arms bent.',
        keyTips: [ { details: 'Do not lock your elbows at the top.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:26,
        name: 'bench press (Close Grip) . dumbbell',
        focusArea: 'triceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'flat bench'}, {name: 'dumbbell'}],
        preperation:'Lie on a bench with feet on the floor. Hold a dumbbell in each hand in a shoulder width neutral grip at the height of the chest with arms bent.',
        keyTips: [ { details: 'Do not lock your elbows at the top.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:27,
        name: 'biceps curl . cable',
        focusArea: 'biceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'cable machine'}],
        preperation:'Stand and hold the bar connected to the low pully in an underhand grip and shoulder width apart with elbows tucked to your sides.',
        keyTips: [ { details: 'Do not bounce back.'},{ details: 'Keep your chest up and eyes looking forward throughout the exercise.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:28,
        name: 'biceps curl . dumbbell',
        focusArea: 'biceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'dumbbell'}],
        preperation:'Stand with feet shoulder width apart. Hold a dumbbell in each hand in an underhand grip with arms extended at your sides and elbows tucked to your sides.',
        keyTips: [ { details: 'Keep your chest up and eyes looking forward throughout the exercise.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:1,
        name: 'bicep curl . barbell',
        focusArea: 'biceps',
        img: './images/biceps/bicepCurlIcon.jpg',
        detailedImage: './images/biceps/bicepCurl.jpg',
        equipment: [{name: 'Barbell'}],
        preperation:'Stand with your chest up. Hold the barbell in an underhand grip with hands shoulder width apart and elbows tucked to your sides.',
        keyTips: [ {details: 'Do not lock your elbows at the top.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:29,
        name: 'concentration curl . dumbbell',
        focusArea: 'biceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'dumbbell'},{name: 'flat bench'}],
        preperation:'Sit on the end of the bench with feet on the floor. Hold a dumbbell in one hand with the elbow against the inner thigh and the arm extended.',
        keyTips: [ { details: 'Keep your upper arm still during the exercise.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:30,
        name: 'crossbody hammer curl . dumbbell',
        focusArea: 'biceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'dumbbell'}],
        preperation:'Stand with feet shoulder width apart. Hold a dymbbell in each hand tucked to your sides with palms facing each other.',
        keyTips: [{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:0,
        name: 'hammer curl . dumbbell',
        focusArea: 'biceps',
        img: './images/biceps/hammerCurlsIcon.png',
        detailedImage: './images/biceps/hammerCurls.png',
        equipment: [{name: 'Dumbbell'}],
        preperation:'Stand with feet shoulder width apart. Hold a dumbbell in each hand in front of your thighs with palms facing each other. Extend arms tucked to your sides',
        keyTips: [ {details: 'Keep a straight back and braced core during the exercise.'}, { details: 'Keep your elbows still to your sides throughout the movement'}],
    },
    {
        id:31,
        name: 'incline bicep curl . dumbbell',
        focusArea: 'biceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'dumbbell'},{name: 'incline bench'}],
        preperation:'Lie on a bench with feet on the floor. Hold a dumbbell in each hand in a neutral grip with arms hang straight down at your sides.',
        keyTips: [{ details: 'Keep your upper arms still during the exercise.'}],
    },
    {
        id:32,
        name: 'overhead triceps extention . cable',
        focusArea: 'triceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'cable machine'}],
        preperation:'Stand with feet shoulder width apart. Hold the handles behind the back of your head with arms bent and elbows lifted.',
        keyTips: [{ details: 'Keep your upper arms still and in line with your body.'},{ details: 'Do not lock your elbows at the top.'},{ details: 'Do not shrug your shoulders throughout the movement.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:33,
        name: 'overhead triceps extention . dumbbell',
        focusArea: 'triceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'dumbbell'}],
        preperation:'Stand with feet shoulder width apart. Hold the handles behind the back of your head with arms bent and elbows lifted.',
        keyTips: [{ details: 'Keep your upper arms still and in line with your body.'},{ details: 'Do not lock your elbows at the top.'},{ details: 'Do not shrug your shoulders throughout the movement.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:34,
        name: 'preacher curl . barbell',
        focusArea: 'biceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'preacher bench'},{name: 'barbell'}],
        preperation:'Sit on a bench with feet on the floor. Hold the barbell in a shoulder width underhand grip with arms extended against the pad.',
        keyTips: [{ details: 'Keep your back straight and upper arms still during the exercise.'},{ details: 'Do not lock your elbows during the exercise.'}],
    },
    {
        id:35,
        name: 'preacher curl . dumbbell',
        focusArea: 'biceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'preacher bench'},{name: 'dumbbell'}],
        preperation:'Sit on a bench with feet on the floor. Hold a dumbbell using one hand in an underhand grip with the arm extended against the pad.',
        keyTips: [{ details: 'Keep your back straight and upper arms still during the exercise.'},{ details: 'Do not lock your elbows during the exercise.'}],
    },
    {
        id:36,
        name: 'skull crusher . barbell',
        focusArea: 'triceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'flat bench'},{name: 'barbell'}],
        preperation:'Lie on a bench with feet on the floor. Hold a bar in an overhand grip with arms bent and elbows lifted.',
        keyTips: [{ details: 'Keep your arms still and close to your head throughout the movement.'},{ details: 'Do not lock your elbows at the top.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:37,
        name: 'skull crusher . dumbbell',
        focusArea: 'triceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'flat bench'},{name: 'dumbbell'}],
        preperation:'Lie on a bench with feet on the floor. Hold a dumbbell in each hand in a neutral grip with arms bent and elbows lifted.',
        keyTips: [{ details: 'Keep your arms still and close to your head throughout the movement.'},{ details: 'Do not lock your elbows at the top.'},{ details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:38,
        name: 'triceps dip',
        focusArea: 'triceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'bodyweight'}],
        preperation:'Keep your torso upright with your feet crossed below the body. Hold a bar in each hand with your arms straight and elbows tight.',
        keyTips: [{ details: 'Keep your legs stationary throughout the movement.'},{ details: 'Keep a straight back during the exercise.'}],
    },
    {
        id:39,
        name: 'triceps dip on bench',
        focusArea: 'triceps',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'bodyweight'}],
        preperation:'Put a bench behind your back and grip the edge next to your hips with your torso upright. Stretch your arms with fingers facing forward and elbows tight.',
        keyTips: [{ details: 'Keep your torso upright and legs extended.'},{ details: 'Keep a straight back during the exercise.'},{ details: 'To increase difficulity, put your legs on another bench in front of you.'}],
    },
    {
        id:4,
        name: 'lateral raise . dumbbell',
        focusArea: 'shoulder',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'Dumbbell'}],
        preperation:'Stand with feet shoulder width apart. Hold a dumbbell in each hand in a neutral grip next to your thighs.',
        keyTips: [ {details: 'Do not shrug your shoulders when raising arms up.'}, { details: 'Keep your elbows slightly bent throughout the movement.'}, { details: 'Keep a straight back and braced core during the exercise.'}],
    },
    {
        id:40,
        name: 'Arlond Press . Dumbbell',
        focusArea: 'shoulder',
        img: './images/shoulder/lateralRaiseIcon.jpg',
        detailedImage: './images/shoulder/lateralRaise.jpg',
        equipment: [{name: 'dumbbell, flat bench'}],
        preperation:'Sit on a bench with feet on the floor. Hold a dumbbell in each hand with elbows bent at around 45 degrees at your sides and palms facing your body.',
        keyTips: [{ details: 'Do not lock your elbows at the top.'},{ details: 'Keep a straight back and braced core during the exercise.'},{ details: 'Do not rest the barbell on your shoulder.'}],
    },
]